name: StarvalEconomy
version: '${version}'
main: de.starvalcity.starvaleconomy.Core
softdepend:
  - LiquidStarval
api-version: 1.16
authors: [ 1337Nirflector ]
description: Economy Plugin for StarvalCity
website: https://starvalcity.de/

commands:
  atm:
    usage: /atm
  bank:
    usage: /bank
  money:
    usage: /money
  payday:
    usage: /payday